### ISSUE TITLE
Make this app releasable

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-nodejs-api#92]
We should be going for a releasable application. In this issue I'd like to list and complete all the necessary things that have to be done before the first release is possible. The final product of this issue should be a versioned release of the API.

**TODO**

- [x] Publish wt-js-libs and move it from a submodule js library to an npm dependency - https://github.com/windingtree/wt-js-libs/issues/105 - #98
- [x] Resolve any absolutely necessary issues if there are any.
- [x] Enforce node version with .nvm file - https://github.com/creationix/nvm
- [x] Enforce node version with engine field in package.json - https://docs.npmjs.com/files/package.json#engines
- [x] Contribution guidelines - https://github.com/blog/1184-contributing-guidelines - #95
- [ ] Up to date documentation in README
- [x] Eslint - #96

I think our distribution form of choice should be GitHub releases.

**Comment by czervenka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release Alpha version](https://trello.com/c/Wnt7Wg64/8-release-alpha-version)
